purecircle_main:
    path:     /
    defaults: { _controller: purecircleMainBundle:Default:index }


purecircle_login:
    path:     /login
    defaults: { _controller: purecircleMainBundle:Default:login}

purecircle_logout:
    path: /logout
    
login_check:
    path: /login_check
   
purecircle_error:
    path:     /login
    defaults: { _controller: purecircleMainBundle:Default:error}   
   