purecircle_admin_user:
    resource: "@purecircleAdminBundle/Resources/config/routing/user.yml"
    prefix:   /admin/user

purecircle_admin_county:
    resource: "@purecircleAdminBundle/Resources/config/routing/county.yml"
    prefix:   /admin/county

purecircle_admin_user:
    resource: "@purecircleAdminBundle/Resources/config/routing/user.yml"
    prefix:   /

purecircle_dash:
    path:     /county
    defaults: { _controller: purecircleAdminBundle:Admin:index }
            

