security:
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext  
      purecircle\AdminBundle\Entity\User:
        algorithm: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_ADMIN: [ ROLE_USER,ROLE_ALLOWED_TO_SWITCH ]
    providers:
        chain_provider:
            chain:
                providers: [ in_memory, administrators ]               
        in_memory:
            memory:
                users: 
                   SUPERBOSS: { password: admin, roles: ROLE_ADMIN }
                   
        administrators:
            entity: { class: purecircleAdminBundle:User, property: username }
    firewalls:
        admin_area:
            switch_user: ~
            pattern: ^/.*
            
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /county
            logout:
                path: /logout
                target: /login
            security: true
            anonymous: true 
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/county, roles: ROLE_USER }